### ISSUE TITLE
BUILD_PREBUILT issue on Copperhead OS on N

### ISSUE THREAD

**Issue by CaseyBakey** [opengapps/aosp_build#84] opened 2016-09-15 12:19 UTC
Hello there,

I'm trying to integrate opengapps into AOSP N (CopperheadOS) and I'm encountering the following issue:

`build/core/Makefile:34: *** Prebuilt apk found in PRODUCT_COPY_FILES: vendor/opengapps/sources/all/app/com.google.android.gm/14/nodpi/58454699.apk:system/app/com.google.android.gm/14/nodpi/58454699.apk, use BUILD_PREBUILT instead!.`

I did try to naively edit vendor/googlel/build/opengapps-files.mk to change from PRODUCT_COPY_FILES to BUILD_PREBUILT, but it's not working either:

`build/core/prebuilt.mk:88: vendor/opengapps/sources/all/etc/sysconfig/whitelist_com.android.omadm.service.xml:system/etc/sysconfig/whitelist_com.android.omadm.service.xml: No such file or directory`

Any idea on this?

**Comment by Blystad** [comment] 2016-09-15 13:02
That shouldn't happen. We use BUILD_PREBUILT for all apps ( See: https://github.com/opengapps/aosp_build/blob/master/core/prebuilt_apk.mk ). For files we use PRODUCT_COPY_FILES ( See: https://github.com/opengapps/aosp_build/blob/master/opengapps-files.mk )

Does CopperheadOS modify the `build` folder in any way?

**Comment by CaseyBakey** [comment] 2016-09-15 13:31
Yeah it seems, here are two commits that seem related:

https://github.com/CopperheadOS/platform_build/commit/9d0488db0933af89f73c113845dcc5aafaffb2ff

https://github.com/CopperheadOS/platform_build/commit/1dc35961548113ca0428efa0d4ecc60582a80a3c

But I must admit I don't really understand what they imply. Is a workaround possible to still match these "requirements" ?

**Comment by Blystad** [comment] 2016-09-15 13:38
That's just a change related to disabling the JIT. Which seems they wanted to disable, for some reason.

If you go to vendor/google/module/Gmail and run `mm` does it still fail?

**Comment by CaseyBakey** [comment] 2016-09-15 13:55
I don't have such a folder because of pico package but I did run `mm` in vendor/google/build/modules/GoogleContacts and I get response from Ubuntu saying I should install multimail :p

**Comment by Blystad** [comment] 2016-09-15 13:58
You need to run 

source build/envsetup.sh
lunch blablabla

then mm works :)

**Comment by CaseyBakey** [comment] 2016-09-15 14:04
Oups, yes, my bad. Was a new terminal without env variables set.

Once I strat mm, I get the exact same error about whitelist_com.android.omadm.service.xml

**Comment by CaseyBakey** [comment] 2016-09-16 15:00
Any other idea to try?

**Comment by BrianAllred** [comment] 2016-09-19 13:01
I can confirm the same problem.

**Comment by Blystad** [comment] 2016-09-26 21:12
Really strange that this happens...but as it only happens on CopperheadOS and not on AOSP builds, it must be that CopperheadOS does something strange.

I don't have the resources to dig fully into this, but what I would do in this scenario is to add logging to the build system, particularly around `build/core/Makefile:34` and `build/core/prebuilt.apk`

Just dump various variables:

E.g.:
```
$(info got $(PRODUCT_COPY_FILES))
```

**Comment by CaseyBakey** [comment] 2016-09-26 23:36
Yeah, I can understand that you don't have time for that and that's a pity for us ;p

I did however try some things with `build/core/Makefile` and `build/core/prebuilt.mk` (not apk ;-) ) but nothing conclusive. Btw, it seems that these 2 files a

**Comment by Blystad** [comment] 2016-09-27 12:06
The AOSP build system has numerous extension points. I see that CopperheadOS adds another one in `device/qcom/common` (I think). It's possible to override build tasks in this way. Might be that this happens somewhere.

https://github.com/CopperheadOS/platform_build/commit/3f7088a38c37f38274e6835e4d16a36a04a36bb4

Regarding PRODUCT_COPY_FILES vs BUILD_PREBUILT, PRODUCT_COPY_FILES is a simple way to copy text/binary files to the system image. E.g.

```
PRODUCT_COPY_FILES += my_file.txt:system/etc/my_file.txt
```

The build system aggregates all of these, and then convert them into makefile jobs.

BUILD_PREBUILT is a build action, so the format on that is a bit different. It's

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := MyModule
LOCAL_SRC_FILES := my_file.txt
include $(BUILD_PREBUILT)
```

Ish ...

We do this in `vendor/google/build/core/prebuilt_apk.mk`

**Comment by AdFad666** [comment] 2016-09-27 20:07
This is not a Copperhead OS problem as I'm building it almost daily with GApps built in.

**Comment by CaseyBakey** [comment] 2016-09-27 23:00
@AdFad666 Ah ah ah, I just don't see how you can't encounter the same error. I'm exactly doing this, but in the `device/lge/bullhead/device.mk`

You don't play with anything else to include opengapps to your build tree?

**Comment by AdFad666** [comment] 2016-09-28 07:32
Nothing special, just those definitions linked above.

Our vendor folder also makes extensive use of `BUILD_PREBUILT` see:
[Contortrix/vendor-sony/kitakami-common/proprietary/Android.mk](https://github.com/Contortrix/vendor-sony/blob/nougat-release/kitakami-common/proprietary/Android.mk#L26)

The only thing I can think if is that there is a typo somewhere in your vendor folder. Can you try a test build without your vendor folder to see if it starts building?

**Comment by CaseyBakey** [comment] 2016-09-28 17:16
When I don't add opengapps (via modifications to device.mk), I'm able to build the whole CopperheadOS Nougat (for N5X/bullhead) without any hitches, including the default vendor partition. And I was able to do it with the opengapps with CopperheadOS Marshmallow.

**Comment by AdFad666** [comment] 2016-09-28 21:13
Hmmmm then I have no idea, all I can say is it works for me :confused:

**Comment by CaseyBakey** [comment] 2016-09-28 21:29
That's funny since your device is not even supported by default by Copperhead :p 

I just did a repo sync on my build tree, and build it again. No problem at all without opengapps. And adding opengapps thanks to this repo (just by adding the few lines to `device/lge/bullhead/device.mk` and `.repo/manifest.xml`), I'm stuck with the same errors.

Should convert the whole PRODUCT_COPY_FILES from opengapps to a BUILD_PREBUILT action help?

I admit I'm eager to try CopperheadOS Nougat, and I tought everything would work fine with opengapps since I didn't encounter any hitch with Marshmallow ⭕ 

I know this issue doesn't seem to be only linked to aosp_build, but I would be glad if it can stay open until a solution is found ;)

**Comment by Blystad** [comment] 2016-09-28 22:08
Couple of things you could try:

1) Delete the contents of `opengapps-files.mk` (just echo "" to it). That will remove any PRODUCT_COPY_FILES we have.
2) From `opengapps-packages.mk` - Remove everything from line 4 and onwards.
3) Go into `modules/SetupWizard` and run `mm -B showcommands` and post output.

Also, do you use `bash` while building, or some other shell? Do you build on Ubuntu 14.04 or some other OS?

**Comment by jamuir** [comment] 2016-10-03 18:48
@CaseyBakey : what version of gnu-make are you using to build with?

PRODUCT_COPY_FILES is populated using the function `gapps-copy-to-system`, which in turn calls the following function:

```makefile
define _gapps-all-files-under
$(patsubst ./%,%, \
	$(shell cd "$(GAPPS_SOURCES_PATH)"; cd "$(1)"; \
		find -L $(2) -type f -and -not -name ".*") \
)
endef
```
It might be that this function is not being evaluated correctly by your shell.  Perhaps one of the "cd" commands is failing.  You could try this instead:

```makefile
define _gapps-all-files-under
$(patsubst ./%,%, \
	$(shell cd "$(GAPPS_SOURCES_PATH)" && cd "$(1)" && \
		find -L $(2) -type f -and -not -name ".*") \
)
endef
```
Similar to Blystad's suggestion, I would add the following line at the bottom of `opengapps-files.mk` to figure out what function is adding the "apk" to PRODUCT_COPY_FILES:

```makefile
$(error ***DEBUG*** PRODUCT_COPY_FILES = $(PRODUCT_COPY_FILES))
```

**Comment by CaseyBakey** [comment] 2016-10-04 16:38
Hello there, sorry for the late answer, but the problem is solved.

The reason is the ifdef test in opengapps-files.mk is still not working for me.

Btw, I didn't see your last answer on https://github.com/opengapps/aosp_build/issues/63 stating pittpatt doesn't exist anymore in Nougat.

The mistake I did, was to edit the line containing 'vendor/pittpatt', to take it out, but without adding back 'usr/srec'.

Now, everything is fine. I just get a little popup error on boot stating "There's an internal problem with your device. Contact your manufacturer for details".

It seems to be linked with different values between values ro.build.date, ro.build.date.utc and ro.build.fingerprint of '/system/build.prop' and respectively ro.vendor.build.date, ro.vendor.build.date.utc and ro.vendor.build.fingerprint of '/vendor/build.prop'.

I don't know if it can/has to be fixed on your side or CopperheadOS side.

Here a short post explaining this :
http://forum.xda-developers.com/nexus-6p/help/theres-internal-problem-device-contact-t3246661

Let me know if you want me to open a issue about this.

At least, this one can be closed. Thanks everyone here for help, and sorry for the inconvenience :o

**Comment by jamuir** [comment] 2016-10-04 17:16
> "There's an internal problem with your device. Contact your manufacturer for details".

That doesn't have anything to do with OpenGapps.

It will go away if you rebuild after doing "make installclean".

Incremental builds can cause the fingerprint value used on one of the partitions to be updated (e.g. the system fingerprint might be updated, and then it will no longer match the vendor fingerprint).

**Comment by CaseyBakey** [comment] 2016-10-04 18:44
Ah ah, nice! Thank you!

I'm trying this right now.

The AOSP building world is a maze: getting lost and learning/remembering everyday ;p

**Comment by Blystad** [comment] 2016-10-04 21:25
If you build a engineering build, instead of a user/userdebug build then that message will also not show :)

**Comment by CaseyBakey** [comment] 2016-10-04 22:10
So I just did finish to make a full new build after `make installclean` and `make clean`, but I still get this error message.

aosp_build and opengapps repos are up-to-date. Any idea?

And I'm doing a user build, to have dm-verity etc.

**Comment by CaseyBakey** [comment] 2016-10-05 15:38
Ok perfect! Everything is working fine, even on latest AOSP/CopperheadOS branch ´nougat-bugfix-release´. No warning on boot etc.

Thanks everyone for your patience and help!

The strange stuff which is still there, is just that my build isn't taking the good branch with the ifdef in opengapps-files.mk. It may only be linked to CopperheadOS behavior. 

Did someone tried with pure AOSP N?

**Comment by jamuir** [comment] 2016-10-05 17:37
we use the stock aosp build system and have no issues adding open gapps to Nougat.

sounds like this issue can be closed.

**Comment by Blystad** [comment] 2016-10-05 18:03
Good that the issue was solved. Closing :)

**Closed by Blystad** 2016-10-05 18:03 UTC
