### ISSUE TITLE
Android-x86 nougat-x86

### ISSUE THREAD

**Issue by harkaman** [opengapps/aosp_build#177] opened 2018-04-17 16:44 UTC
Got this issue since afew days ago.

```
including ./vendor/opengapps/build/modules/AndroidPlatformServices/Android.mk ...
including ./vendor/opengapps/build/modules/Books/Android.mk ...
including ./vendor/opengapps/build/modules/CalculatorGoogle/Android.mk ...
including ./vendor/opengapps/build/modules/CalendarGooglePrebuilt/Android.mk ...
including ./vendor/opengapps/build/modules/Chrome/Android.mk ...
lunzip: Output file 'vendor/opengapps/sources/x86_64/app/com.android.chrome/24/nodpi/332510962.apk' already exists, skipping.
including ./vendor/opengapps/build/modules/CloudPrint2/Android.mk ...
including ./vendor/opengapps/build/modules/DMAgent/Android.mk ...
including ./vendor/opengapps/build/modules/Drive/Android.mk ...
including ./vendor/opengapps/build/modules/EditorsDocs/Android.mk ...
including ./vendor/opengapps/build/modules/EditorsSheets/Android.mk ...
including ./vendor/opengapps/build/modules/EditorsSlides/Android.mk ...
including ./vendor/opengapps/build/modules/FaceLock/Android.mk ...
including ./vendor/opengapps/build/modules/FitnessPrebuilt/Android.mk ...
including ./vendor/opengapps/build/modules/GCS/Android.mk ...
including ./vendor/opengapps/build/modules/GoogleBackupTransport/Android.mk ...
including ./vendor/opengapps/build/modules/GoogleCalendarSyncAdapter/Android.mk ...
including ./vendor/opengapps/build/modules/GoogleCamera/Android.mk ...
vendor/opengapps/build/core/prebuilt_apk.mk:50: *** Unable to find APK for GoogleCamera.
build/core/ninja.mk:163: recipe for target 'out/build-android_x86_64.ninja' failed
make: *** [out/build-android_x86_64.ninja] Error 1
make: Leaving directory '/media/harkama/ANDROID-x86/nougat-x86'
```

**Comment by jamuir** [comment] 2018-04-17 16:54
the error is intentional and is caused by a recent change.

We are planning a new change to give users an easy way to work around this.

In the meantime, you can read here:

https://github.com/opengapps/aosp_build/pull/175

**Comment by jamuir** [comment] 2018-04-24 23:59
#178 was just merged.  When an invalid module is detected, an error message is emitted with a suggestion to use `GAPPS_EXCLUDED_PACKAGES` as a work around.

**Closed by jamuir** 2018-04-24 23:59 UTC
