### ISSUE TITLE
Could not build FEC data! Error: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc & system image is out of space

### ISSUE THREAD

**Issue by tamilselvik** [opengapps/aosp_build#60] opened 2016-06-07 07:13 UTC
I am trying to build android N code for flounder device. I am getting the following error. Kindly please help, 

[ 88% 40323/45738] Target system fs image: out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img
FAILED: /bin/bash -c "(mkdir -p out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/ out/target/product/flounder/obj/PACKAGING/systemimage_intermediates && rm -rf out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"fs_type=ext4\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_size=2782920704\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"userdata_fs_type=f2fs\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"cache_fs_type=ext4\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"cache_size=268435456\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"extfs_sparse_flag=-s\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"squashfs_sparse_flag=-s\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"selinux_fc=out/target/product/flounder/root/file_contexts.bin\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"boot_signer=false\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity=true\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_key=build/target/product/security/verity\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_signer_cmd=verity_signer\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"verity_fec=true\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"system_verity_block_device=/dev/block/platform/sdhci-tegra.3/by-name/APP\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"vendor_verity_block_device=/dev/block/platform/sdhci-tegra.3/by-name/VNR\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (echo \"skip_fsck=true\" >>  out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt ) && (PATH=out/host/linux-x86/bin/:\$PATH ./build/tools/releasetools/build_image.py out/target/product/flounder/system out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system_image_info.txt out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img out/target/product/flounder/system || ( echo \"Out of space? the tree size of out/target/product/flounder/system is (MB): \" 1>&2 ; du -sm out/target/product/flounder/system 1>&2; if [ \"ext4\" == \"ext4\" ]; then maxsize=2782920704; if [ \"\" == \"true\" ]; then maxsize=\$((maxsize - 4096 * 4096)); fi; echo \"The max is \$(( maxsize / 1048576 )) MB.\" 1>&2 ; else echo \"The max is \$(( 2782920704 / 1048576 )) MB.\" 1>&2 ; fi; mkdir -p out/dist; cp out/target/product/flounder/installed-files.txt out/dist/installed-files-rescued.txt; exit 1 ) )"

error: failed to build out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img from out/target/product/flounder/system
Running:  mkuserimg.sh -s out/target/product/flounder/system out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img ext4 system 2739474432 -D out/target/product/flounder/system -L system out/target/product/flounder/root/file_contexts.bin
make_ext4fs -s -T -1 -S out/target/product/flounder/root/file_contexts.bin -L system -l 2739474432 -a system out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img out/target/product/flounder/system out/target/product/flounder/system
Creating filesystem with parameters:
    Size: 2739474432
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7968
    Inode size: 256
    Journal blocks: 10450
    Label: system
    Blocks: 668817
    Block groups: 21
    Reserved block group size: 167
Created filesystem with 2133/167328 inodes and 233530/668817 blocks
build_verity_tree -A aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7 out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img /tmp/tmphjpKsV_verity_images/verity.img
system/extras/verity/build_verity_metadata.py 2739474432 /tmp/tmphjpKsV_verity_images/verity_metadata.img afeb5dcc51a79493469bc5557de66090066d65223224d17f54b99a034c78a550 aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7 /dev/block/platform/sdhci-tegra.3/by-name/APP verity_signer build/target/product/security/verity.pk8
cat /tmp/tmphjpKsV_verity_images/verity_metadata.img >> /tmp/tmphjpKsV_verity_images/verity.img
fec -e out/target/product/flounder/obj/PACKAGING/systemimage_intermediates/system.img /tmp/tmphjpKsV_verity_images/verity.img /tmp/tmphjpKsV_verity_images/verity_fec.img
Could not build FEC data! Error: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Aborted (core dumped)
Out of space? the tree size of out/target/product/flounder/system is (MB): 
827	out/target/product/flounder/system
The max is 2654 MB.
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1

#### make failed to build some targets (12:12:56 (hh:mm:ss)) ####

**Comment by Blystad** [comment] 2016-06-07 08:25
This doesn't look like an issue caused by OpenGapps AOSP Build.

```
Could not build FEC data! Error: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Aborted (core dumped)
Out of space? the tree size of out/target/product/flounder/system is (MB): 
827 out/target/product/flounder/system
The max is 2654 MB.
```

Maybe you ran out of RAM? Does it build fine without OpenGapps AOSP Build?

I'm not 100% sure how the system will work with Ninja and Kati (N build system), as I havn't tested this. The N source code isn't released in full yet.

**Comment by tamilselvik** [comment] 2016-06-07 08:43
Hi Blystad,

Thanks for the reply,

Actually its not related to OpenGapps. Sorry for posting in this forum. 
I thought someone might have got this error and have solution for building the android open source project.

**Comment by Blystad** [comment] 2016-06-07 08:58
You could try this google group, related to Android building: https://groups.google.com/forum/#!forum/android-building

**Closed by Blystad** 2016-06-07 08:58 UTC

**Comment by tamilselvik** [comment] 2016-06-07 09:01
I will try it. Thanks Blystad.
