### ISSUE TITLE
Phone recognized as Pixel in Google Photos

### ISSUE THREAD

**Issue by vasilmkd** [opengapps/aosp_build#134] opened 2017-05-06 07:52 UTC
Nexus 6 build with stock OpenGapps package. There are no build.prop tweaks, yet the phone is recognized as a Pixel in Google Photos, which doesn't let me change the backup type. My Google Drive storage gets depleted every time I backup a photo.

It is a user build, so I have no root. Any suggestions?

**Comment by mfonville** [comment] 2017-05-06 08:45
Ah, I recently changed the file `/etc/sysconfig/nexus.xml` to be again as it is on Pixel devices. It is just important that this file should **only** be installed on Pixel devices and not on ROMs for other devices. Aosp_build will need an update to take this into account.

**Comment by vasilmkd** [comment] 2017-05-06 09:02
But if I manually delete the two strings before my build, I should be in the clear right?

**Comment by mfonville** [comment] 2017-05-06 09:11
yes, but even better would be to completely drop the file if it ain't a pixel, to avoid issues with setupwizard too (since android 7.1)

**Comment by vasilmkd** [comment] 2017-05-06 09:13
Right, because the setup wizard is also Pixel-esque! Thank you very much!

**Comment by mfonville** [comment] 2017-05-06 09:18
no problem, but not sure if closing the issue is the right thing; the aosp_build script needs an update for this so probably @Blystad wants to have a look at this

**Comment by Blystad** [comment] 2017-05-08 12:31
Right now we just blindly take everything from all/etc. I guess we only want "google.xml" by default. Then Nexus users can add their own PRODUCT_COPY_FILES for the other files, if they so desire.

**Closed** 2018-03-06 23:55 UTC
